name: Go
on:
  push:
    paths:
      - '**/*.go'
      - go.mod
      - go.sum
      - benchmark/*.go
      - benchmark/go.mod
      - benchmark/go.sum
      - Makefile
      - .github/workflows/go.yml
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.25.x"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: test
        run: |
          make vet
          make test

      - name: benchmark
        run: |
          go test -C benchmark -modfile=go.mod -bench=. -benchmem -benchtime=3s -cpu=1,2,4
