name: Go
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24.x", "1.25.x"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: test
        run: |
          make vet
          make test

      - name: benchmark
        run: |
          cd benchmark
          go test -bench=. -benchmem -benchtime=3s -cpu=1,2,4
